CREATE TABLE PLANT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  SPECIES_ID AUTO_INCREMENT
  CREATED timestamp default (CUR TIME()),
);

CREATE TABLE SPECIES (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FOREIGN KEY (plant_id)
  REFERENCES PLANT(id)
  NAME varchar(20),
  SUNLIGHT varchar(20),
  WATER INT,
  NUTRITION INT,
  READY_TO_EAT INT
);



