CREATE TABLE SPECIES (
  SPECIES_ID SERIAL PRIMARY KEY,
  NAME varchar(20),
  SUNLIGHT varchar(20),
  WATER INT,
  NUTRITION INT,
  READY_TO_EAT INT,
  SHORT_INFO VARCHAR(250),
  FULL_INFO VARCHAR(4000)
);

CREATE TABLE PLANT (
  PLANT_ID SERIAL,
  PLANT_NAME VARCHAR(64) NOT NULL,
  SPECIES_ID INT,
  CREATED timestamp default CURRENT_TIMESTAMP,
  PRIMARY KEY(PLANT_ID),
	CONSTRAINT FK_SPECIES
	FOREIGN KEY(SPECIES_ID)
	REFERENCES SPECIES(SPECIES_ID)
);
